inherit_from: .rubocop_todo.yml

require: [ rubocop-rspec ]

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/MultipleMemoizedHelpers:
  Enabled: false
